name: Update Proposal Count, Orgs and Contributors

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - '**/*.pdf'
      - '*/'
      - '.github/workflows/update-proposal-count.yml'
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  update-count:
    runs-on: ubuntu-latest
    # Only run this job if the PR was merged or if it's a direct push to main
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Count PDFs and Get Orgs
        id: count-pdfs
        run: |
          # Count PDF files excluding .git directory
          PDF_COUNT=$(find . -type f -name "*.pdf" ! -path "./.git/*" | wc -l)
          echo "pdf_count=$PDF_COUNT" >> $GITHUB_OUTPUT
          
          # Get list of directories (orgs) excluding special directories
          ORGS=$(find . -maxdepth 1 -type d ! -path . ! -path ./.git ! -path ./.github | sed 's|./||' | sort)
          # Create org checklist
          ORG_LIST=""
          while IFS= read -r org; do
            ORG_LIST="${ORG_LIST}- [x] ${org}\n"
          done <<< "$ORGS"
          # Remove trailing newline and escape for GitHub Actions
          ORG_LIST="${ORG_LIST%\\n}"
          echo "org_list<<EOF" >> $GITHUB_OUTPUT
          echo -e "$ORG_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get Contributor Info
        id: contributor
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          CONTRIBUTOR_NAME="${{ github.event.pull_request.user.name }}"
          if [ -z "$CONTRIBUTOR_NAME" ]; then
            CONTRIBUTOR_NAME="${{ github.event.pull_request.user.login }}"
          fi
          CONTRIBUTOR_URL="${{ github.event.pull_request.user.html_url }}"
          echo "name=$CONTRIBUTOR_NAME" >> $GITHUB_OUTPUT
          echo "url=$CONTRIBUTOR_URL" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          # Use awk to replace the org checklist section
          awk -v orgs="${{ steps.count-pdfs.outputs.org_list }}" '
          /^## Org Submission Checklist/{
            print
            print ""
            print orgs
            found=1
            next
          }
          found && /^[[:space:]]*$/{found=0}
          !found{print}
          ' README.md > README.tmp && mv README.tmp README.md
          
          # Update the proposal count
          sed -i "s/Total proposals submitted: \*\*[0-9]\+\*\*/Total proposals submitted: **${{ steps.count-pdfs.outputs.pdf_count }}**/" README.md
          
          # Add new contributor if this is a merged PR and contributor isn't already listed
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            CONTRIBUTOR_LINE="- [${{ steps.contributor.outputs.name }}](${{ steps.contributor.outputs.url }})"
            if ! grep -q "${{ steps.contributor.outputs.url }}" README.md; then
              sed -i "/^## Contributors/a\\${CONTRIBUTOR_LINE}" README.md
            fi
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              git commit -m "Update README with new contributor ${{ steps.contributor.outputs.name }}"
            else
              git commit -m "Update proposal count to ${{ steps.count-pdfs.outputs.pdf_count }} and update org list"
            fi
          )
          git push 